version: "3.8"
services:
  prtg:
    image: prtg:22.1.75
    labels:
      caddy: ${SUBDOMAIN}.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy
      - prtg_net
      - prtg-test-drive_default
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

networks:
  caddy:
    external: true
  prtg_net:
  prtg-test-drive_default:
    external: true